### ISSUE TITLE
Unable to import GhostHandLib when installing from Cocoapods

### ISSUE THREAD

**Issue by cste3244** [mds6058/GhostHand#1]
Hello -

I came across your library and it looks promising. Unfortunately when attempting to install from Cocoapods I'm unable to import the library, GhostHandLib.

It doesn't look like it packaged the pod correctly and is missing the GhostHand.swift file.

**Comment by mattstanford** [comment]
Thanks, I missed that (I am using this with Carthage on one of my projects). I believe I fixed the issue, please try it with GhostHand 1.0.1.
